services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: change_this
      POSTGRES_DB: db
    volumes:
      - local-pgdata:/var/lib/postgresql/data
    ports:
      - "8080:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: change_this
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local-pgdata:
  pgadmin-data:
