services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db
    volumes:
      - local-pgdata:/var/lib/postgresql/data
    ports:
      - "8080:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_USER_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
volumes:
  local-pgdata:
  pgadmin-data:
